
import javax.swing.JOptionPane;
import java.util.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NSH
 */
public class MainFrame extends javax.swing.JFrame {
    String btngetData;
    String btngetpData;
    static double MemoryValue;
    static int ilData;
    static int irData;
    static int iresult;
    static double dlData;
    static double drData;
    static double dresult;
    static double result;
    static String ckid;
    static int ascSym;
    int itData;
    double dbData;
    static char Symbol = ' ';
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton24 = new javax.swing.JButton();
        txt_Result = new javax.swing.JTextField();
        btn_C = new javax.swing.JButton();
        btn_Sqrt = new javax.swing.JButton();
        btn_Divide = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_CE = new javax.swing.JButton();
        btn_BackSpace = new javax.swing.JButton();
        btn_MC = new javax.swing.JButton();
        btn_MR = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_Multiply = new javax.swing.JButton();
        btn_Persent = new javax.swing.JButton();
        btn_MS = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_Sub = new javax.swing.JButton();
        btn_Fountain = new javax.swing.JButton();
        btn_M = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_Add_Sub = new javax.swing.JButton();
        btn_Dot = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();
        btn_Equals = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        txt_SaveResult = new javax.swing.JTextField();

        jButton24.setText("jButton24");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_Result.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        txt_Result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Result.setText("0");

        btn_C.setText("C");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });

        btn_Sqrt.setText("sqrt");
        btn_Sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SqrtActionPerformed(evt);
            }
        });

        btn_Divide.setText("/");
        btn_Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DivideActionPerformed(evt);
            }
        });

        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_CE.setText("CE");
        btn_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CEActionPerformed(evt);
            }
        });

        btn_BackSpace.setText("Backspace");
        btn_BackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackSpaceActionPerformed(evt);
            }
        });

        btn_MC.setText("MC");
        btn_MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MCActionPerformed(evt);
            }
        });

        btn_MR.setText("MR");
        btn_MR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MRActionPerformed(evt);
            }
        });

        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_Multiply.setText("*");
        btn_Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultiplyActionPerformed(evt);
            }
        });

        btn_Persent.setText("%");
        btn_Persent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PersentActionPerformed(evt);
            }
        });

        btn_MS.setText("MS");
        btn_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MSActionPerformed(evt);
            }
        });

        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_Sub.setText("-");
        btn_Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubActionPerformed(evt);
            }
        });

        btn_Fountain.setText("1/x");
        btn_Fountain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FountainActionPerformed(evt);
            }
        });

        btn_M.setText("M+");
        btn_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MActionPerformed(evt);
            }
        });

        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_Add_Sub.setText("+/-");
        btn_Add_Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_SubActionPerformed(evt);
            }
        });

        btn_Dot.setText(".");
        btn_Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DotActionPerformed(evt);
            }
        });

        btn_Add.setText("+");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Equals.setText("=");
        btn_Equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EqualsActionPerformed(evt);
            }
        });

        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        txt_SaveResult.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        txt_SaveResult.setForeground(new java.awt.Color(153, 153, 153));
        txt_SaveResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_SaveResult)
                    .addComponent(txt_Result, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_BackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_MC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_MR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Persent, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Fountain, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_M, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Add_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_SaveResult, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Persent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Fountain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_M, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean isIDck(double num){     //true-int, false-double
        return num % 1==0.0;
    }
    
    private void tStr(String btngetData){
        if(it_db_Str(btngetData)){
            txt_Result.setText(Double.toString(dbData));
        }else{
            txt_Result.setText(Integer.toString(itData));
        }
    }    
    private boolean it_db_Str(String btngetData){//true-double, false-int
        if(btngetData.contains(".")){
            return true;
        }else{
            return false;
        }
    }
    private void ChackIf(double str){
        if(isIDck(result)){//true-int, false-double
                iresult = (int)result;
                txt_SaveResult.setText(Integer.toString(iresult)+Symbol);
                txt_Result.setText("0");
            }else{
                txt_SaveResult.setText(Double.toString(result)+Symbol);
                txt_Result.setText("0");
            }
    }
    
    private void sw4(int cr, char Sym){
        switch(cr){
                case 43:
                    result=Double.parseDouble(txt_SaveResult.getText().substring(0, txt_SaveResult.getText().length()-1))+Double.parseDouble(btngetData);
                    Symbol = Sym;
                    ChackIf(result);
                    break;
                case 42:
                    if(txt_SaveResult.getText().substring(txt_SaveResult.getText().length()-1, txt_SaveResult.getText().length())=="="){
                        txt_SaveResult.setText(btngetData+Sym);
                        break;
                    }
                    result=Double.parseDouble(txt_SaveResult.getText().substring(0, txt_SaveResult.getText().length()-1))*Double.parseDouble(btngetData);
                    Symbol = Sym;
                    ChackIf(result);
                    break;
                case 45:
                    if(txt_SaveResult.getText().substring(txt_SaveResult.getText().length()-1, txt_SaveResult.getText().length())=="="){
                        txt_SaveResult.setText(btngetData+Sym);
                        break;
                    }
                    result=Double.parseDouble(txt_SaveResult.getText().substring(0, txt_SaveResult.getText().length()-1))-Double.parseDouble(btngetData);
                    Symbol = Sym;
                    ChackIf(result);
                    break;
                case 47:
                    if(txt_SaveResult.getText().substring(txt_SaveResult.getText().length()-1, txt_SaveResult.getText().length())=="="){
                        txt_SaveResult.setText(btngetData+Sym);
                        break;
                    }
                    result=Double.parseDouble(txt_SaveResult.getText().substring(0, txt_SaveResult.getText().length()-1))/Double.parseDouble(btngetData);
                    Symbol = Sym;
                    ChackIf(result);
                    break;
                default:
                    break;
            }
    }
    private double onlysw(int cr){
        int idx;
        switch(cr){
                case 43:
                    idx = txt_SaveResult.getText().indexOf('+');
                    result=Double.parseDouble(txt_SaveResult.getText().substring(0, idx))+Double.parseDouble(btngetData);
                    return result;
                case 42:
                    idx = txt_SaveResult.getText().indexOf('*');
                    result=Double.parseDouble(txt_SaveResult.getText().substring(0, idx))*Double.parseDouble(btngetData);
                    return result;
                case 45:
                    idx = txt_SaveResult.getText().indexOf('-');
                    result=Double.parseDouble(txt_SaveResult.getText().substring(0, idx))-Double.parseDouble(btngetData);
                    return result;
                case 47:
                    idx = txt_SaveResult.getText().indexOf('/');
                    result=Double.parseDouble(txt_SaveResult.getText().substring(0, idx))/Double.parseDouble(btngetData);
                    return result;
                default:
                    return result;
            }
    }
    
    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        if(Symbol == ' '){
            Symbol = btn_Add.getText().charAt(0);            
            btngetData += Symbol;
            txt_SaveResult.setText(btngetData);
            txt_Result.setText("0");
        }else if(Symbol == '+'){
            result=Double.parseDouble(txt_SaveResult.getText().substring(0, txt_SaveResult.getText().length()-1))+Double.parseDouble(btngetData);
            ChackIf(result);
        }else{
            ascSym = (int)Symbol;
            sw4(ascSym, btn_Add.getText().charAt(0));
        }
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        if(Symbol == ' '){
            Symbol = btn_Sub.getText().charAt(0);            
            btngetData += Symbol;
            txt_SaveResult.setText(btngetData);
            txt_Result.setText("0");
        }else if(Symbol == '-'){
            result=Double.parseDouble(txt_SaveResult.getText().substring(0, txt_SaveResult.getText().length()-1))-Double.parseDouble(btngetData);
            ChackIf(result);
        }else{
            ascSym = (int)Symbol;
            sw4(ascSym,btn_Sub.getText().charAt(0));
            Symbol = btn_Sub.getText().charAt(0);
        }
    }//GEN-LAST:event_btn_SubActionPerformed

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        // TODO add your handling code here:
        txt_Result.setText("0");
        txt_SaveResult.setText(null);
        Symbol=' ';
        ascSym = 0;     
        iresult = 0;
        result = 0;
    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_0.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        if(it_db_Str(btngetData)){
            txt_Result.setText(btngetData);
        }else{
            txt_Result.setText(Integer.toString(itData));
        }
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_1.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_2.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_3.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_4.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_5.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_6.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_7.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_8.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetData += btn_9.getText();
        dbData = Double.parseDouble(btngetData);
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_Add_SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_SubActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        dbData = Double.parseDouble(btngetData);
        dbData *= -1;
        itData = (int)dbData;
        tStr(btngetData);
    }//GEN-LAST:event_btn_Add_SubActionPerformed

    private void btn_DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DotActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        if(!btngetData.contains(".")){
            btngetData += btn_Dot.getText();
            txt_Result.setText(btngetData);
        }
    }//GEN-LAST:event_btn_DotActionPerformed

    private double equalsw(int cr){
        int idx;
        int idx2;
        switch(cr){
                case 43:
                    idx = txt_SaveResult.getText().indexOf('+');
                    idx2 = txt_SaveResult.getText().indexOf('=');
                    result=Double.parseDouble(btngetData)+Double.parseDouble(txt_SaveResult.getText().substring(idx+1, idx2));
                    return result;
                case 42:
                    idx = txt_SaveResult.getText().indexOf('*');
                    idx2 = txt_SaveResult.getText().indexOf('=');
                    result=Double.parseDouble(btngetData)*Double.parseDouble(txt_SaveResult.getText().substring(idx+1, idx2));
                    return result;
                case 45:
                    idx = txt_SaveResult.getText().indexOf('-');
                    idx2 = txt_SaveResult.getText().indexOf('=');
                    result=Double.parseDouble(btngetData)-Double.parseDouble(txt_SaveResult.getText().substring(idx+1, idx2));
                    return result;
                case 47:
                    idx = txt_SaveResult.getText().indexOf('/');
                    idx2 = txt_SaveResult.getText().indexOf('=');
                    result=Double.parseDouble(btngetData)/Double.parseDouble(txt_SaveResult.getText().substring(idx+1, idx2));
                    return result;
                default:
                    return result;
            }
    }
    private int idxsw(int ascSym){
        int idx;
        switch(ascSym){
                case 43:
                    idx = txt_SaveResult.getText().indexOf('+');
                    return idx;
                case 42:
                    idx = txt_SaveResult.getText().indexOf('*');
                    return idx;
                case 45:
                    idx = txt_SaveResult.getText().indexOf('-');
                    return idx;
                case 47:
                    idx = txt_SaveResult.getText().indexOf('/');
                    return idx;
                default:
                    return 0;
            }
    }
    
    private void btn_EqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EqualsActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        char equals;
        if(Symbol == ' '){
            equals = btn_Equals.getText().charAt(0);            
            btngetData += equals;
            txt_SaveResult.setText(btngetData);
            txt_Result.setText("0");
        }else{
            int idx;
            char eq = txt_SaveResult.getText().charAt(txt_SaveResult.getText().length()-1);
            if(eq=='='){//rebutton
                ascSym = (int)Symbol;
                result = equalsw(ascSym);
                idx = idxsw(ascSym);
                txt_SaveResult.setText(txt_Result.getText()+Symbol+txt_SaveResult.getText().substring(idx+1,txt_SaveResult.getText().length()-1)+'=');
                if(isIDck(result)){//true-int, false-double
                    iresult = (int)result;
                    txt_Result.setText(Integer.toString(iresult));
                }else{
                    txt_Result.setText(Double.toString(result));
                }
            }else{
                ascSym = (int)Symbol;
                result = onlysw(ascSym);
                txt_SaveResult.setText(txt_SaveResult.getText()+txt_Result.getText()+'=');
                if(isIDck(result)){//true-int, false-double
                    iresult = (int)result;
                    txt_Result.setText(Integer.toString(iresult));
                }else{
                    txt_Result.setText(Double.toString(result));
                }
            }
        }
    }//GEN-LAST:event_btn_EqualsActionPerformed

    private void btn_SqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SqrtActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        dbData = Double.parseDouble(btngetData);
        dbData = Math.sqrt(dbData);
        if(isIDck(dbData)){
            iresult = (int)dbData;
            txt_Result.setText(Integer.toString(iresult));
        }else{
            txt_Result.setText(Double.toString(dbData));
        }
        txt_SaveResult.setText("√("+btngetData+")");
        
    }//GEN-LAST:event_btn_SqrtActionPerformed

    private void btn_MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultiplyActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        if(Symbol == ' '){
            Symbol = btn_Multiply.getText().charAt(0);            
            btngetData += Symbol;
            txt_SaveResult.setText(btngetData);
            txt_Result.setText("0");
        }else if(Symbol == '*'){
            result=Double.parseDouble(txt_SaveResult.getText().substring(0, txt_SaveResult.getText().length()-1))*Double.parseDouble(btngetData);
            ChackIf(result);
        }else{
            ascSym = (int)Symbol;
            sw4(ascSym, btn_Multiply.getText().charAt(0));
        }
    }//GEN-LAST:event_btn_MultiplyActionPerformed

    private void btn_DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DivideActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        if(Symbol == ' '){
            Symbol = btn_Divide.getText().charAt(0);            
            btngetData += Symbol;
            txt_SaveResult.setText(btngetData);
            txt_Result.setText("0");
        }else if(Symbol == '/'){
            result=Double.parseDouble(txt_SaveResult.getText().substring(0, txt_SaveResult.getText().length()-1))/Double.parseDouble(btngetData);
            ChackIf(result);
        }else{
            ascSym = (int)Symbol;
            sw4(ascSym,btn_Divide.getText().charAt(0));
        }
    }//GEN-LAST:event_btn_DivideActionPerformed

    private void btn_BackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackSpaceActionPerformed
        // TODO add your handling code here:
        txt_Result.setText(txt_Result.getText().substring(0,txt_Result.getText().length()-1));
    }//GEN-LAST:event_btn_BackSpaceActionPerformed

    private void btn_PersentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PersentActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        btngetpData = txt_SaveResult.getText();
        char ck = btngetpData.charAt(btngetpData.length()-1);
        if(!(ck >= 48 && ck <= 57)){//true-number, false-math
            btngetpData = btngetpData.substring(0, btngetpData.length()-1);
            result = Double.parseDouble(btngetpData);
            
        }else{
            
        }
    }//GEN-LAST:event_btn_PersentActionPerformed

    private void btn_FountainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FountainActionPerformed
        // TODO add your handling code here:
        btngetData = txt_Result.getText();
        dbData = Double.parseDouble(btngetData);
        dbData = 1/dbData;
        if(isIDck(dbData)){
            iresult = (int)dbData;
            txt_Result.setText(Integer.toString(iresult));
        }else{
            txt_Result.setText(Double.toString(dbData));
        }
        txt_SaveResult.setText("1/("+btngetData+")");
        
    }//GEN-LAST:event_btn_FountainActionPerformed

    private void btn_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CEActionPerformed
        // TODO add your handling code here:
        txt_Result.setText("0");
    }//GEN-LAST:event_btn_CEActionPerformed

    private void btn_MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MCActionPerformed
        // TODO add your handling code here:
        MemoryValue = '\n';
    }//GEN-LAST:event_btn_MCActionPerformed

    private void btn_MRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MRActionPerformed
        // TODO add your handling code here:
        if(MemoryValue!='\n'){
            if(isIDck(MemoryValue)){//true-int, false-double
                int data = (int)MemoryValue;
                txt_Result.setText(Integer.toString(data));
            }else{
                txt_Result.setText(Double.toString(MemoryValue));
            }
        }
    }//GEN-LAST:event_btn_MRActionPerformed

    private void btn_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MSActionPerformed
        // TODO add your handling code here:
        MemoryValue = Double.parseDouble(txt_Result.getText());
    }//GEN-LAST:event_btn_MSActionPerformed

    private void btn_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MActionPerformed
        // TODO add your handling code here:
        if(MemoryValue!='\n'){
            MemoryValue += Double.parseDouble(txt_Result.getText());
        }
    }//GEN-LAST:event_btn_MActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Add_Sub;
    private javax.swing.JButton btn_BackSpace;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_CE;
    private javax.swing.JButton btn_Divide;
    private javax.swing.JButton btn_Dot;
    private javax.swing.JButton btn_Equals;
    private javax.swing.JButton btn_Fountain;
    private javax.swing.JButton btn_M;
    private javax.swing.JButton btn_MC;
    private javax.swing.JButton btn_MR;
    private javax.swing.JButton btn_MS;
    private javax.swing.JButton btn_Multiply;
    private javax.swing.JButton btn_Persent;
    private javax.swing.JButton btn_Sqrt;
    private javax.swing.JButton btn_Sub;
    private javax.swing.JButton jButton24;
    private javax.swing.JTextField txt_Result;
    private javax.swing.JTextField txt_SaveResult;
    // End of variables declaration//GEN-END:variables
}

